spring:
  application:
    name: spring-lab

server:
  port: 8080

app:
  owner: Azhar Alimbay
  group: It1-2410 IS
  mail:
    from: 40801@iitu.edu.kz
    retry-count: 3
    timeout: 5s
    enabled: true
  export:
    formats: [ "PDF", "XLSX", "CSV" ]
    max-rows: 50000

logging:
  level:
    kz.iitu: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"